/*
 * FLASH_commands.h
 *
 *  Created on: 11 paź 2020
 *      Author: NeghM
 */

#ifndef EXT_FLASH_H_
#define EXT_FLASH_H_

#define EXT_FLASH_COMMAND_READ_ARRAY	0x03
#define EXT_FLASH_COMMAND_WRITE_PAGE	0x02

#define EXT_FLASH_COMMAND_ERASE_4K		0x20
#define EXT_FLASH_COMMAND_ERASE_32K		0x52
#define EXT_FLASH_COMMAND_ERASE_64K		0xd8
#define EXT_FLASH_COMMAND_ERASE_ALL		0x60

#define EXT_FLASH_COMMAND_WRITE_ENABLE	0x06
#define EXT_FLASH_COMMAND_WRITE_DISABLE	0x04

#define EXT_FLASH_MAX_PAGE_SIZE		256

#define EXT_FLASH_4K_BLOKS_NBR		256
#define EXT_FLASH_32K_BLOKS_NBR		32
#define EXT_FLASH_64K_BLOKS_NBR		16

#endif /* EXT_FLASH_H_ */
